modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
[[mods]]
modId="hydraulic"
version="${version}"
displayName="Hydraulic"
logoFile="hydraulic.png"
authors="GeyserMC"
description='''${description}'''
[[dependencies.hydraulic]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.hydraulic]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"