[versions]
mixin = "0.8.5"
geyser = "2.1.0-SNAPSHOT"

[libraries]
mixin = { group = "org.spongepowered", name = "mixin", version.ref = "mixin" }
geyser-api = { group = "org.geysermc.geyser", name = "api", version.ref = "geyser" }
geyser-core = { group = "org.geysermc.geyser", name = "core", version.ref = "geyser" }
auto-service = { group = "com.google.auto.service", name = "auto-service", version = "1.0.1" }
