modLoader="javafml"
loaderVersion="[1,)"
license="MIT"
[[mods]]
modId="hydraulic"
version="${version}"
displayName="Hydraulic"
logoFile="hydraulic.png"
authors="GeyserMC"
description='''${description}'''
[[mixins]]
config = "hydraulic.mixins.json"
[[dependencies.hydraulic]]
    modId="neoforge"
    type="required"
    versionRange="[20.4.48-beta,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.hydraulic]]
    modId="minecraft"
    type="required"
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
