name: Build Pull Request

on:
  pull_request:
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/*.yml'
      - '.github/actions/build.yml'
      - '.idea/copyright/*.xml' 
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        # See https://github.com/actions/checkout/commits
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          submodules: recursive

      - name: Validate Gradle Wrapper
        # See https://github.com/gradle/wrapper-validation-action/commits
        uses: gradle/wrapper-validation-action@b231772637bb498f11fdbc86052b6e8a8dc9fc92 # v2.1.2

        # See https://github.com/actions/setup-java/commits
      - uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
        with:
          java-version: 21
          distribution: temurin
          
      - name: Build
        # See https://github.com/gradle/gradle-build-action/commits
        uses: gradle/gradle-build-action@ebc47c299ce5f6b106c1663c8c99ab07e0ce1666 # v3.1.0
        with:
          arguments: build
          gradle-home-cache-cleanup: true
          
      - name: Archive artifacts (Hydraulic Fabric)
        # See https://github.com/actions/upload-artifact/commits
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        if: success()
        with:
          name: Hydraulic Fabric
          path: fabric/build/libs/hydraulic-fabric.jar
          if-no-files-found: error
      - name: Archive artifacts (Hydraulic NeoForge)
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3
        if: success()
        with:
          name: Hydraulic NeoForge
          path: neoforge/build/libs/hydraulic-neoforge.jar
          if-no-files-found: error